name = "Sebaxu"
# To generate a new UUID for your package, open the Julia REPL,
# type `using UUIDs` and then run `uuid4()`.
uuid = "950ad09b-307f-438b-9b61-dfcb3fec248a" 
authors = ["Sahraoui Tarik Ziad <sahraouitrikziad@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"
Plots = "1"